import { Service, NewsItem, Review, BankRate } from "./types";

export const BANKING_PARTNERS = [
  "LIC Housing Finance Ltd (LIC HFL)",
  "Federal Bank",
  "IDBI Bank",
  "Indian Bank",
  "Bank of Baroda",
  "Repco Home Finance",
  "GIC Housing Finance Ltd.",
  "Aadhar Housing Finance Ltd.",
  "Karnataka Bank Ltd",
  "South Indian Bank",
  "Mahindra Home Finance",
  "Piramal Finance",
  "DCB Bank",
  "Punjab National Bank",
  "PNB Housing Finance Limited",
  "Fedbank Financial Services Limited",
  "Kotak Mahindra Bank",
  "Karur Vysya Bank (KVB)",
  "Truhome Finance",
  "Sundaram Home Finance (Sundaram Finance)",
  "Axis Finance",
  "Bajaj Housing Finance",
  "Manappuram Finance Limited",
  "Bajaj Finserv",
  "Godrej Capital",
  "YES Bank",
  "ICICI Home Finance",
  "Aditya Birla Capital Home Loans",
  "Orange Retail Finance",
  "Vastu Housing Finance",
  "IKF Home Finance",
  "Union Bank of India",
  "Tata Capital",
  "ICICI Bank"
];

export const INITIAL_BANK_RATES: BankRate[] = [
  {
    id: "rate-1",
    bankNameEn: "LIC Housing Finance Ltd (LIC HFL)",
    bankNameMl: "എൽ.ഐ.സി ഹൗസിംഗ് ഫിനാൻസ് (LIC HFL)",
    interestRate: "8.35% - 8.75%",
    maxTenureEn: "35 Years",
    maxTenureMl: "35 വർഷം",
    processingFeeEn: "0.25% (Min ₹10,000)",
    processingFeeMl: "0.25% (കുറഞ്ഞത് ₹10,000)",
    updatedAt: "2026-05-26"
  },
  {
    id: "rate-2",
    bankNameEn: "Federal Bank",
    bankNameMl: "ഫെഡറൽ ബാങ്ക്",
    interestRate: "8.40% - 9.10%",
    maxTenureEn: "30 Years",
    maxTenureMl: "30 വർഷം",
    processingFeeEn: "0.50% of Loan Amount",
    processingFeeMl: "വായ്പ തുകയുടെ 0.50%",
    updatedAt: "2026-05-26"
  },
  {
    id: "rate-3",
    bankNameEn: "State Bank of India (SBI)",
    bankNameMl: "സ്റ്റേറ്റ് ബാങ്ക് ഓഫ് ഇന്ത്യ (SBI)",
    interestRate: "8.40% - 9.25%",
    maxTenureEn: "30 Years",
    maxTenureMl: "30 വർഷം",
    processingFeeEn: "0.35% (Max ₹15,000)",
    processingFeeMl: "0.35% (പരമാവധി ₹15,000)",
    updatedAt: "2026-05-26"
  },
  {
    id: "rate-4",
    bankNameEn: "Bank of Baroda",
    bankNameMl: "ബാങ്ക് ഓഫ് ബറോഡ",
    interestRate: "8.40% - 9.35%",
    maxTenureEn: "30 Years",
    maxTenureMl: "30 വർഷം",
    processingFeeEn: "0.50% (Max ₹20,000)",
    processingFeeMl: "0.50% (പരമാവധി ₹20,000)",
    updatedAt: "2026-05-26"
  },
  {
    id: "rate-5",
    bankNameEn: "South Indian Bank",
    bankNameMl: "സൗത്ത് ഇന്ത്യൻ ബാങ്ക്",
    interestRate: "8.55% - 9.60%",
    maxTenureEn: "30 Years",
    maxTenureMl: "30 വർഷം",
    processingFeeEn: "0.50% (Min ₹5,000)",
    processingFeeMl: "0.50% (കുറഞ്ഞത് ₹5,000)",
    updatedAt: "2026-05-26"
  },
  {
    id: "rate-6",
    bankNameEn: "Canara Bank",
    bankNameMl: "കനറാ ബാങ്ക്",
    interestRate: "8.45% - 9.50%",
    maxTenureEn: "30 Years",
    maxTenureMl: "30 വർഷം",
    processingFeeEn: "0.50% of Loan Amount",
    processingFeeMl: "വായ്പ തുകയുടെ 0.50%",
    updatedAt: "2026-05-26"
  }
];

export const INITIAL_SERVICES: Service[] = [
  {
    id: "hfl-core",
    titleEn: "Housing Loans & Refinanacing",
    titleMl: "ഭവന വായ്പകളും പുനർവായ്പകളും",
    descEn: "Customized residential mortgage solutions with low interest rates and flexible tenures from LIC HFL and leading banks.",
    descMl: "LIC HFL-ൽ നിന്നും പ്രമുഖ ബാങ്കുകളിൽ നിന്നും കുറഞ്ഞ പലിശനിരക്കിലും ലളിതമായ വ്യവസ്ഥകളിലും ഭവന വായ്പകൾ.",
    detailEn: "We assist in home building loans, plot purchase loans, home extension, and refinancing solutions with hassle-free documentation. Supporting you at every step of your legal audit, property valuation, and final disbursement.",
    detailMl: "വീട് നിർമ്മാണം, സ്ഥലം വാങ്ങൽ, വീട് വിപുലീകരണം എന്നിവയ്ക്കുള്ള റീഫിനാൻസിംഗ് സ്കീമുകൾ ഞങ്ങൾ വേഗത്തിൽ ലഭ്യമാക്കുന്നു. പ്രമാണ പരിശോധന മുതൽ തുക അനുവദിക്കുന്നതുവരെയുള്ള എല്ലാ ഘട്ടങ്ങളിലും വ്യക്തിഗത മേൽനോട്ടം ഉറപ്പുനൽകുന്നു.",
    icon: "Home"
  },
  {
    id: "lap-credit",
    titleEn: "Loan Against Property (LAP)",
    titleMl: "വസ്തുവകകളിന്മേലുള്ള വായ്പകൾ (LAP)",
    descEn: "Unlock the liquid value of your residential or commercial properties to fund business expansion or personal needs.",
    descMl: "കച്ചവട ആവശ്യങ്ങൾക്കോ വ്യക്തിഗത ആവശ്യങ്ങൾക്കോ നിങ്ങളുടെ വസ്തുവകകളുടെ അടിസ്ഥാനത്തിൽ മികച്ച പലിശയിൽ ദീർഘകാല വായ്പകൾ.",
    detailEn: "Get maximum valuation on your collateral property with customized payback tenors and high repayment flexibility. Ideal for self-employed professionals, traders, and small business owners.",
    detailMl: "നിങ്ങളുടെ ഉടമസ്ഥതയിലുള്ള വസ്തുവകകൾക്ക് പരമാവധി മൂല്യം നിർണ്ണയിച്ചു മികച്ച തിരിച്ചടവ് കാലാവധികളിൽ വായ്പ ഉറപ്പാക്കുന്നു. വ്യാപാരികൾക്കും ചെറുകിട ബിസിനസ്‌ സംരംഭകർക്കും ഇത് കൂടുതൽ അനുയോജ്യമാണ്.",
    icon: "Briefcase"
  },
  {
    id: "comm-project",
    titleEn: "Commercial Real Estate & Project Loans",
    titleMl: "വാണിജ്യ വായ്പകളും പ്രോജക്ട് ലോണുകളും",
    descEn: "Structured commercial funding solutions for office space acquisition, industrial growth, and commercial property development.",
    descMl: "വാണിജ്യ സ്ഥാപനങ്ങൾ വാങ്ങുന്നതിനും, നിർമ്മാണങ്ങൾക്കും, വ്യാവസായിക വളർച്ചയ്ക്കുമായി വലിയ തോതിലുള്ള വായ്പാ സേവനങ്ങൾ.",
    detailEn: "We structure corporate credit terms, construction finance for builders, and commercial space purchase programs aligned with major financial institutions for optimal rates.",
    detailMl: "വ്യാവസായിക സ്ഥാപനങ്ങൾക്കും ബിൽഡർമാർക്കും പ്രോജക്ട് വിലയിരുത്തലുകൾ നടത്തി ആവശ്യമായ കൺസ്ട്രക്ഷൻ ഫിനാൻസിംഗും കൊമേഴ്ഷ്യൽ വായ്പകളും കുറഞ്ഞ നൂലാമാലകളോടെ അറേഞ്ച് ചെയ്തു നൽകുന്നു.",
    icon: "Building"
  },
  {
    id: "financial-adv",
    titleEn: "Comprehensive Financial Planning",
    titleMl: "സമഗ്ര ധനകാര്യ പ്ലാനിംഗ്",
    descEn: "Tailored advice across insurance portfolio optimization, smart asset accumulation, and goal-based security setups.",
    descMl: "ഇൻഷുറൻസ് സുരക്ഷ, ദീർഘകാല സാമ്പത്തിക നിക്ഷേപം, കുടുംബത്തിന്റെ ഭാവി ഭദ്രതയ്ക്കായുള്ള സമഗ്രമായ ഉപദേശങ്ങൾ.",
    detailEn: "Professional guidance to structure and secure your generational wealth. Integrating risk hedging strategies through premium LIC insurance packages and smart mutual assets planning.",
    detailMl: "നിങ്ങളുടെ കഠിനാധ്വാനത്തിലൂടെ ഉണ്ടാക്കിയ സമ്പാദ്യം ഏറ്റവും സുരക്ഷിതമായി നിക്ഷേപിക്കാനും സംരക്ഷിക്കാനും ഇൻഷുറൻസ് പരിരക്ഷയോടെയുള്ള വിദഗ്ദ്ധ ഉപദേശങ്ങൾ ലഭ്യമാക്കുന്നു.",
    icon: "ShieldCheck"
  }
];

export const INITIAL_NEWS: NewsItem[] = [
  {
    id: "news-1",
    titleEn: "How to Secure Prime Housing Loan Rates in 2026",
    titleMl: "2026-ൽ ഏറ്റവും കുറഞ്ഞ പലിശയിൽ ഭവന വായ്പ എങ്ങനെ സ്വന്തമാക്കാം?",
    contentEn: "The mortgage rates landscape has changed over the past quarters. Learn how your credit history, debt-to-income ratio, and correct property documentation from authorities like LIC HFL can save you lakhs of Indian Rupees in your overall interest payout.",
    contentMl: "ഭവന വായ്പകളുടെ പലിശ നിരക്കുകളിൽ വലിയ മാറ്റങ്ങളാണ് വന്നുകൊണ്ടിരിക്കുന്നത്. എൽ.ഐ.സി ഹൗസിംഗ് ഫിനാൻസ് മുഖേന കൃത്യമായ രേഖകളോടെ അപേക്ഷിച്ചാൽ ലക്ഷക്കണക്കിന് രൂപ എങ്ങനെ ലാഭിക്കാം എന്ന് സാമ്പത്തിക വിദഗ്ദ്ധൻ പ്രവീൺ കുമാർ വിശദീകരിക്കുന്നു.",
    date: "2026-05-20",
    authorEn: "Praveen Kumar P",
    authorMl: "പ്രവീൺ കുമാർ പി",
    categoryEn: "Housing Loans",
    categoryMl: "ഭവന വായ്പകൾ",
    image: "https://picsum.photos/seed/loan/800/600"
  },
  {
    id: "news-2",
    titleEn: "The Importance of Getting Property Legal Clearance First",
    titleMl: "ആദ്യം വസ്തുവിന്റെ നിയമപരമായ അനുമതി (Legal Clearance) ഉറപ്പാക്കുക",
    contentEn: "Legal safety of your property transaction is paramount. Before committing payments to a builder or seller, perform essential legal checks such as Encumbrance Certificate validation, Land Tax receipts audit, and layout approvals from municipal bodies.",
    contentMl: "ഒരു വസ്തുവകയോ ഭവനമോ തിരഞ്ഞെടുക്കുമ്പോൾ അതിന്റെ ലീഗൽ ക്ലിയറൻസ് ഉറപ്പാക്കേണ്ടത് അത്യാവശ്യമാണ്. എൻകംബ്രൻസ് സർട്ടിഫിക്കറ്റ്, ലാൻഡ് ടാക്സ് രസീതുകൾ എന്നിവ കൃത്യമായി പരിശോധിച്ചില്ലെങ്കിൽ ഭാവിയിൽ വായ്പ നേടുന്നതിൽ ഉണ്ടായേക്കാവുന്ന ബുദ്ധിമുട്ടുകൾ ഇവയാണ്.",
    date: "2026-05-15",
    authorEn: "Praveen Kumar P",
    authorMl: "പ്രവീൺ കുമാർ പി",
    categoryEn: "Advisory News",
    categoryMl: "നിയമ ഉപദേശം",
    image: "https://picsum.photos/seed/legal/800/600"
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: "rev-1",
    name: "Dr. Rajesh K. Nair",
    designationEn: "Associate Professor, Palakkad",
    designationMl: "അസോസിയേറ്റ് പ്രൊഫസർ, പാലക്കാട്",
    feedbackEn: "Mr. Praveen Kumar's guidance made our villa clearance and home loan sanction processed in less than 10 working days. Unmatched professional integrity and quick documentation process!",
    feedbackMl: "പ്രവീൺ കുമാറിന്റെ കൃത്യമായ മാർഗ്ഗനിർദ്ദേശം കൊണ്ട് ഞങ്ങളുടെ വീട്ടുവായ്പ വെറും 10 ദിവസത്തിനുള്ളിൽ മുൻവിധികളില്ലാതെ ലഭ്യമായി. അതിവേഗത്തിലുള്ള ഫയൽ വർക്കുകളും പൂർണ്ണമായ വിശ്വസ്തതയും!",
    rating: 5,
    date: "2026-05-24",
    approved: true
  },
  {
    id: "rev-2",
    name: "Meera Krishnan",
    designationEn: "IT consultant, Infopark",
    designationMl: "ഐ.ടി കൺസൾട്ടന്റ്, ഇൻഫോപാർക്ക്",
    feedbackEn: "I was struggling with high interest home loans elsewhere. Praveen suggested an excellent refinancing solution with Federal Bank which brought down my EMI costs drastically.",
    feedbackMl: "മറ്റൊരു ബാങ്കിലെ ഉയർന്ന പലിശയുള്ള ഹൗസിംഗ് ലോൺ ഫെഡറൽ ബാങ്കിലേക്ക് മാറ്റി റീഫിനാൻസ് ചെയ്യാൻ പ്രവീൺ സഹായിച്ചു. വലിയ രീതിയിലാണ് പലിശഭാരം കുറഞ്ഞത്. മികച്ച സേവനം!",
    rating: 5,
    date: "2026-05-18",
    approved: true
  },
  {
    id: "rev-3",
    name: "Najeemuddin Palakkad",
    designationEn: "Managing Director, NM Builders",
    designationMl: "മാനേജിംഗ് ഡയറക്ടർ, എൻ എം ബിൽഡേഴ്‌സ്",
    feedbackEn: "For commercial project approvals and retail mortgage tie-ups, Praveen Kumar is the ultimate professional in Kerala. Highly responsive and exceptionally logical with files.",
    feedbackMl: "ഞങ്ങളുടെ കൊമേഴ്സ്യൽ ബിൽഡിംഗുകളുടെ പ്രോജക്ട് ഫിനാൻസിംഗിനും കസ്റ്റമർമാർക്കുള്ള ഹോം ലോണിനും ഞങ്ങൾ ആശ്രയിക്കുന്നത് പ്രവീണിനെയാണ്. വളരെ വിശ്വസിക്കാവുന്ന വ്യക്തി.",
    rating: 5,
    date: "2026-04-29",
    approved: true
  }
];

export const TRANSLATIONS = {
  en: {
    navHome: "Home",
    navServices: "Services",
    navNews: "Financial Insights",
    navContact: "Contact",
    navAdmin: "Admin Panel",
    welcomeTitle: "Praveen Kumar P",
    welcomeSubtitle: "Senior Wealth Specialist, Housing Finance & Insurance Advisor",
    tagline: "25 years of professional legacy in housing loans, life & health insurance protection, and smart investment portfolios across South India.",
    experienceBadge: "25+ Years of Legacy",
    certifiedBadge: "LIC HFL, Insurance & Banking Advisor",
    heroCTA1: "Explore Loan & Insurance",
    heroCTA2: "Schedule Advisory",
    aboutTitle: "A Professional Legacy Built on Trust",
    aboutDescription: "With a distinguished 25-year career spanning housing finance, medical and life insurance consulting, and smart investment portfolios, Praveen Kumar P is a prominent name in financial planning in Kerala. Partnering with LIC HFL, major public/private sector banks, and elite insurance underwriters, he provides stress-free, comprehensive asset protection and mortgage options.",
    partnersTitle: "Our Verified Banking & Finance Partners",
    partnersSubtitle: "Access premier rates through our trusted relationships with India's largest banking and housing finance institutions",
    coreServicesTitle: "Our Professional Advisory Portfolios",
    coreServicesSubtitle: "Customized structures for commercial, mortgage, insurance & generational asset planning",
    readDetail: "Read Portfolio Details",
    closeDetail: "Close Details",
    newsHeading: "Financial Advisor News & Market Insights",
    newsSub: "Keep up-to-date with current mortgage policies, RBI lending rates, and Kerala property laws",
    readMore: "Read Full Article",
    reviewsHeading: "Client Experience & Ratings",
    reviewsSub: "What homeowners, business leads, and property developers say about our services",
    leaveReview: "Share Your Experience",
    reviewName: "Your Full Name",
    reviewDesignation: "Designation / Location",
    reviewRating: "Select Stars Rating",
    reviewFeedback: "Your Comments/Message",
    reviewSubmit: "Submit Review for Reviewers",
    reviewSuccess: "Review submitted successfully! It will be listed once verified by the admin.",
    contactHeading: "Get Direct Advisory & Quick Enquiry",
    contactSub: "Feel free to drop your queries. Receive full legal review of your mortgage documents in 24 hours.",
    formName: "Full Name",
    formPhone: "Mobile / WhatsApp Number",
    formEmail: "Email Address",
    formSubject: "Type of Enquiry (e.g., LIC Housing Loan)",
    formMsg: "Tell us about your requirement or property location",
    formBtn: "Send Enquiry via Email Client",
    formSuccess: "Form compiled! Launching mail client to complete the message transmit.",
    officeAddress: "LIC Office Location",
    homeAddress: "Private Registry Residence",
    phoneLabel: "Phone",
    emailLabel: "Email",
    addressLabel: "Address",
    directionLink: "Get Directions via Google Maps",
    adminTitle: "Authorized Management Center",
    loginDesc: "Enter administrative credentials to proceed with managing page articles, services, and live client feedback.",
    loginBtn: "Authenticate Securely",
    passcodeLabel: "Admin Access Passcode",
    wrongPasscode: "Invalid security passcode. Please verify or check configurations.",
    logoutBtn: "Secure Log Out",
    addServiceBtn: "Add Advisory Portfolio",
    addNewsBtn: "Publish Market Insight",
    deleteBtn: "Delete",
    editBtn: "Edit Component",
    approvedLabel: "Approved",
    approveBtn: "Approve for Public Portal",
    newServiceHeading: "Create New Service Offering",
    newNewsHeading: "Write New Financial Article",
    adminSubtitle: "Admin Session active. Content additions are immediately stored in the live database.",
    titleLabel: "Title En",
    titleMlLbl: "Title Malayalam (മലയാളം)",
    descLabel: "Short Description En",
    descMlLbl: "Description Malayalam (മലയാളം)",
    detailLabel: "Detailed Specs En",
    detailMlLbl: "Detailed Specs Malayalam (മലയാളം)",
    categoryLabel: "Category (e.g., Policy Updates)",
    contentLabel: "Article Content En",
    contentMlLbl: "Article Content Malayalam (മലയാളം)",
    saveBtn: "Save Content",
    cancelBtn: "Discard"
  },
  ml: {
    navHome: "ഹോം",
    navServices: "സേവനങ്ങൾ",
    navNews: "ധനകാര്യ വിവരങ്ങൾ",
    navContact: "ബന്ധപ്പെടുക",
    navAdmin: "അഡ്മിൻ പാനൽ",
    welcomeTitle: "പ്രവീൺ കുമാർ പി",
    welcomeSubtitle: "സീനിയർ വെൽത്ത് സ്പെഷ്യലിസ്റ്റ്, ഹൗസിംഗ് ലോൺ & ഇൻഷുറൻസ് കൺസൾട്ടന്റ്",
    tagline: "ഭവന വായ്പകൾ, ലൈഫ് & ഹെൽത്ത് ഇൻഷുറൻസ് സുരക്ഷ, ഹ്രസ്വ/ദീർഘകാല നിക്ഷേപങ്ങൾ എന്നിവയിലെ 25 വർഷത്തെ സുതാര്യമായ സേവന പാരമ്പര്യം.",
    experienceBadge: "25+ വർഷത്തെ വിശ്വസ്തത",
    certifiedBadge: "LIC HFL, ഇൻഷുറൻസ് & ബാങ്കിംഗ് അഡ്വൈസർ",
    heroCTA1: "ലോൺ & ഇൻഷുറൻസ് സേവനങ്ങൾ",
    heroCTA2: "ഒരു അപ്പോയിന്റ്മെന്റ് എടുക്കാം",
    aboutTitle: "വിശ്വാസ്യതയും വ്യക്തതയും നിറഞ്ഞ 25 വർഷത്തെ പാരമ്പര്യം",
    aboutDescription: "ഹൗസിംഗ് ഫിനാൻസ് രംഗത്തും ലൈഫ്-മെഡിക്കൽ ഇൻഷുറൻസ് തന്ത്രങ്ങളിലും സാമ്പത്തിക ആസൂത്രണത്തിലും 25 വർഷത്തിലേറെ പ്രവർത്തനപരിചയമുള്ള പ്രവീൺ കുമാർ പി നിങ്ങളുടെ സാമ്പത്തിക സുരക്ഷിതത്വം ഉറപ്പുവരുത്താൻ പ്രവർത്തിക്കുന്നു. LIC HFL, പ്രമുഖ പൊതു/സ്വകാര്യ ബാങ്കുകൾ, രാജ്യത്തെ ഇൻഷുറൻസ് പ്രൊവൈഡർമാർ എന്നിവരുമായുള്ള സഹകരണത്തിലൂടെ ലളിതവും കാര്യക്ഷമവുമായ കൺസൾട്ടേഷൻ ലഭ്യമാക്കുന്നു.",
    partnersTitle: "ഞങ്ങളുടെ പ്രധാന ധനകാര്യ പങ്കാളികൾ",
    partnersSubtitle: "ഇന്ത്യയിലെ പ്രമുഖ ബാങ്കുകളുമായും ഹൗസിംഗ് ഫിനാൻസ് കമ്പനികളുമായും ചേർന്നുള്ള വിശ്വസ്ത സേവനം",
    coreServicesTitle: "സാമ്പത്തിക കൺസൾട്ടേഷൻ മേഖലകൾ",
    coreServicesSubtitle: "നിങ്ങളുടെ ബിസിനസ്സ്, ഹൗസിംഗ്, സാമ്പത്തിക അടിത്തറ ശക്തമാക്കാനുള്ള പ്രൊഫഷണൽ രീതികൾ",
    readDetail: "വിശദമായ വിവരങ്ങൾ",
    closeDetail: "വിവരങ്ങൾ മറയ്ക്കുക",
    newsHeading: "പ്രവീൺ കുമാറിന്റെ ധനകാര്യ നിരൂപണങ്ങൾ",
    newsSub: "പലിശ നിരക്കുകളിലെ മാറ്റങ്ങൾ, ആർ ബി ഐ ലോൺ നയങ്ങൾ, നിയമ വശങ്ങൾ എന്നിവ എളുപ്പത്തിൽ മനസിലാക്കൂ",
    readMore: "പൂർണ്ണമായി വായിക്കുക",
    reviewsHeading: "ഉപഭോക്താക്കളുടെ അഭിപ്രായങ്ങൾ",
    reviewsSub: "ഞങ്ങളുടെ ഉപഭോക്താക്കൾ പറയുന്ന മാന്യവും വിശ്വസ്തവുമായ അനുഭവസാക്ഷ്യങ്ങൾ",
    leaveReview: "നിങ്ങളുടെ അഭിപ്രായം രേഖപ്പെടുത്തൂ",
    reviewName: "നിങ്ങളുടെ പേര്",
    reviewDesignation: "ജോലി / സ്ഥലം",
    reviewRating: "സ്റ്റാർസ് സെലക്ട് ചെയ്യുക",
    reviewFeedback: "അഭിപ്രായങ്ങൾ എഴുതുക",
    reviewSubmit: "അഭിപ്രായം വെരിഫിക്കേഷനായി അയക്കുക",
    reviewSuccess: "റിവ്യൂ വിജയകരമായി സബ്മിറ്റ് ചെയ്തു! അഡ്മിൻ അംഗീകാരത്തിന് ശേഷം ഇത് പേജിൽ കാണിക്കുന്നതാണ്.",
    contactHeading: "നേരിട്ട് ചോദിക്കൂ, സംശയങ്ങൾ തീർക്കൂ",
    contactSub: "ലോണുകൾ സംബന്ധിച്ച നിങ്ങളുടെ ഏതൊരു സംശയത്തിനും 24 മണിക്കൂറിനുള്ളിൽ കൃത്യമായ ലീഗൽ റിവ്യൂ ലഭ്യമാക്കുന്നു.",
    formName: "മുഴുവൻ പേര്",
    formPhone: "മൊബൈൽ / വാട്സ്ആപ്പ് നമ്പർ",
    formEmail: "ഇമെയിൽ വിലാസം",
    formSubject: "എന്തിനെക്കുറിച്ചുള്ള അന്വേഷണം (ഉദാഹരണം: എൽ.ഐ.സി ഹോം ലോൺ)",
    formMsg: "നിങ്ങളുടെ ആവശ്യങ്ങളോ വീടിനായുള്ള സ്ഥലത്തിന്റെ വിശദാംശങ്ങളോ നൽകുക",
    formBtn: "അന്വേഷണം ഇമെയിൽ മുഖേന അയക്കുക",
    formSuccess: "വിവരങ്ങൾ തയ്യാറാണ്! നിങ്ങളുടെ മെയിൽ അയക്കുന്നതിനായി മെയിൽ ക്ലയന്റ് തുറക്കുക.",
    officeAddress: "ഓഫീസ് വിലാസം",
    homeAddress: "സ്വകാര്യ വസതിയിലെ വിലാസം",
    phoneLabel: "ഫോൺ",
    emailLabel: "ഇമെയിൽ",
    addressLabel: "വിലാസം",
    directionLink: "ഗൂഗിൾ മാപ്പ് വഴി ലൊക്കേഷൻ കാണുവാൻ ക്ലിക്ക് ചെയ്യുക",
    adminTitle: "അഡ്മിൻ മാനേജ്‌മെന്റ് സെന്റർ",
    loginDesc: "വെബ്‌സൈറ്റ് ഉള്ളടക്കങ്ങൾ നിയന്ത്രിക്കുന്നതിനായി പാസ്കോഡ് ഉപയോഗിച്ച് സുരക്ഷിതമായി പ്രവേശിക്കുക.",
    loginBtn: "ലോഗിൻ ചെയ്യുക",
    passcodeLabel: "അഡ്മിൻ ആക്സസ്സ് പാസ്കോഡ്",
    wrongPasscode: "തെറ്റായ പാസ്കോഡ് നൽകിയിരിക്കുന്നു. ദയവായി ശരിയായ ഒന്ന് നൽകുക.",
    logoutBtn: "സുരക്ഷിതമായി ലോഗൗട്ട് ചെയ്യുക",
    addServiceBtn: "പുതിയ സേവനം പബ്ലിഷ് ചെയ്യുക",
    addNewsBtn: "പുതിയ ലേഖനം പബ്ലിഷ് ചെയ്യുക",
    deleteBtn: "ഡിലീറ്റ് ചെയ്യുക",
    editBtn: "എഡിറ്റ് ചെയ്യുക",
    approvedLabel: "അംഗീകരിക്കപ്പെട്ടു",
    approveBtn: "റിവ്യൂ വെബ്സൈറ്റിൽ കാണിക്കുക",
    newServiceHeading: "പുതിയ പോർട്ട്‌ഫോളിയോ ആരംഭിക്കുക",
    newNewsHeading: "പുതിയ നിക്ഷേപ ലേഖനം തയ്യാറാക്കുക",
    adminSubtitle: "അഡ്മിൻ ലോഗിൻ സജീവമാണ്. നിങ്ങൾ ചേർക്കുന്ന മാറ്റങ്ങൾ ഉടൻ തന്നെ ഡാറ്റാബേസിൽ അപ്‌ഡേറ്റ് ചെയ്യപ്പെടും.",
    titleLabel: "ലേഖന തലക്കെട്ട് En",
    titleMlLbl: "തലക്കെട്ട് മലയാളത്തിൽ (മലയാളം)",
    descLabel: "ചെറിയ വിവരണം En",
    descMlLbl: "വിവരണം മലയാളത്തിൽ (മലയാളം)",
    detailLabel: "വിശദമായ വിവരം En",
    detailMlLbl: "വിശദമായി മലയാളത്തിൽ (മലയാളം)",
    categoryLabel: "വിഭാഗം (ഉദാഹരണം: ഭവന വായ്പ നയങ്ങൾ)",
    contentLabel: "ലേഖനത്തിന്റെ ഉള്ളടക്കം En",
    contentMlLbl: "ഉള്ളടക്കം മലയാളത്തിൽ (മലയാളം)",
    saveBtn: "പബ്ലിഷ് ചെയ്യുക",
    cancelBtn: "ക്ലോസ്സ് ചെയ്യുക"
  }
};
